"""Updated comments model

Revision ID: 48a9f9d060a1
Revises: 210f44f41103
Create Date: 2019-04-27 12:37:46.120796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a9f9d060a1'
down_revision = '210f44f41103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('review', sa.String(), nullable=True))
    op.drop_column('reviews', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('reviews', 'review')
    # ### end Alembic commands ###
